# Generated by Django 5.1.6 on 2025-02-05 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('repeating_mon', models.BooleanField()),
                ('repeating_tue', models.BooleanField()),
                ('repeating_wed', models.BooleanField()),
                ('repeating_thu', models.BooleanField()),
                ('repeating_fri', models.BooleanField()),
                ('repeating_sat', models.BooleanField()),
                ('repeating_sun', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('event_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.eventseries')),
            ],
        ),
    ]
