# Generated by Django 5.1.6 on 2025-02-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='has_repeats',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
